# Generated by Django 3.2.8 on 2021-10-19 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Separado(a)', 'Separado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viuvo(a)', 'Viuvo(a)'), ('Uniao Estavel', 'Uniao Estavel')], default='Solteiro(a)', max_length=50, null=True)),
                ('ddd', models.CharField(default='55', max_length=3)),
                ('fone', models.CharField(max_length=9, null=True)),
                ('logradouro', models.CharField(max_length=32, null=True)),
                ('numero', models.PositiveIntegerField(null=True, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
    ]
